# ~/.config/starship.toml

 #      _            _ _     _            
 #     | |          (_) |   | |           
 #   __| | _____   ___| | __| | _____   __
 #  / _` |/ _ \ \ / / | |/ _` |/ _ \ \ / /
 # | (_| |  __/\ V /| | | (_| |  __/\ V / 
 #  \__,_|\___| \_/ |_|_|\__,_|\___| \_/  
 #
 # 

add_newline = true

[line_break]
disabled = true

[character]     
 # success_symbol = "[â¯](#636DB0)[â¯](#F2BF1E)[â¯](#3BAD9A)"     
 success_symbol = "[ïƒšâ¯](#3bad9a)"     
 error_symbol = "[ï€](#f64747)" # ï€ï°¸
 vicmd_symbol = "[V](bold green) "

[directory]
format = "[$path ]($style)[$read_only]($read_only_style)" 

[[battery.display]]
threshold = 50
style = "bold red"

[python]
python_binary = "python3"

[time]
disabled = true
time_format = "%R %P"
format = 'ğŸ•™[ $time]($style) '

[conda]
ignore_base = false
format = "$symbol$environment "
